URL_HOME = "http://www.uitestingplayground.com/home"
URL_DYNAMIC_ID = "http://www.uitestingplayground.com/dynamicid"
URL_AJAX = "http://www.uitestingplayground.com/ajax"
URL_CLIENT_DELAY = "http://www.uitestingplayground.com/clientdelay"
URL_TEXT_INPUT = "http://www.uitestingplayground.com/textinput"